[package]
name = "crust"
version = "0.3.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
image = "0.25.6"
macroquad = { version = "0.4.14", features = ["audio"] }
rfd = "0.15.3"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
