[package]
name = "crust"
version = "0.2.1"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.14", features = ["audio"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
