[package]
name = "crust"
version = "0.2.2"
edition = "2024"

[dependencies]
chrono = "0.4.41"
image = "0.25.6"
macroquad = { version = "0.4.14", features = ["audio"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
