site_name: Crust
theme:
  font:
    text: Comic Sans MS
    code: JetBrains Mono
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: custom
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started:
    - Project Setup: project-setup.md
    - Crust (The Programming Language): crust-language.md
    - Functions:
      - Miscellaneous:
        - misc/io.md
        - misc/math.md
        - misc/sprite.md
        - misc/datatypes.md
        - misc/other.md
      - Motion: motion.md
      - Looks: looks.md
      - Sound: sound.md
      - Event: events.md
      - Control: control.md
      - Drawing: drawing.md
      - Window: window.md
    - Running your Crust Project: run.md
  - The Screen: screen.md
  - License: license.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
